# Use an official Node.js runtime as the base image
FROM node:16.20.0

WORKDIR /postgreQuery

COPY package*.json ./
COPY prisma ./prisma/
COPY .env ./

RUN npm install

COPY . . 

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
